import sys
sys.path.insert(0, __import__('os').path.join(__import__('os').path.dirname(__file__), '..', '..'))
from test_utils import Test


def sort_nums_ascending(lst):
    return sorted(lst)





Test.assert_equals(sort_nums_ascending([1, 2, 10, 50, 5]), [1, 2, 5, 10, 50])
Test.assert_equals(sort_nums_ascending([80, 29, 4, -95, -24, 85]), [-95, -24, 4, 29, 80, 85])
Test.assert_equals(sort_nums_ascending([]), [])
Test.assert_equals(sort_nums_ascending([47, 51, -17, -16, 91, 47, -85, -8, -16, -27]), [-85, -27, -17, -16, -16, -8, 47, 47, 51, 91])
Test.assert_equals(sort_nums_ascending([-51, -73, 65, 69, -76, 74, -14]), [-76, -73, -51, -14, 65, 69, 74])
Test.assert_equals(sort_nums_ascending([45, 98, 35, 65, 97, 21, 33]), [21, 33, 35, 45, 65, 97, 98])
Test.assert_equals(sort_nums_ascending([-23, -69, -54, -2, -32]), [-69, -54, -32, -23, -2])
Test.assert_equals(sort_nums_ascending([-21, -9, -96]), [-96, -21, -9])
Test.assert_equals(sort_nums_ascending([0]), [0])
Test.summary()



def sort_word(word):
	return ''.join(sorted(word))



Test.assert_equals(sort_word("dcba"), "abcd")
Test.assert_equals(sort_word("pneumonoultramicroscopicsilicovolcanoconiosis"), "aacccccceiiiiiilllmmnnnnooooooooopprrsssstuuv")
Test.assert_equals(sort_word("Unpredictable"), "Uabcdeeilnprt", "Capital letters should come first!")
Test.assert_equals(sort_word("a"), "a")
Test.assert_equals(sort_word("ability"), "abiilty")
Test.assert_equals(sort_word("able"), "abel")
Test.assert_equals(sort_word("about"), "abotu")
Test.assert_equals(sort_word("above"), "abeov")
Test.assert_equals(sort_word("accept"), "accept")
Test.assert_equals(sort_word("according"), "accdginor")
Test.assert_equals(sort_word("account"), "accnotu")
Test.assert_equals(sort_word("across"), "acorss")
Test.assert_equals(sort_word("act"), "act")
Test.assert_equals(sort_word("action"), "acinot")
Test.assert_equals(sort_word("activity"), "aciittvy")
Test.assert_equals(sort_word("actually"), "aaclltuy")
Test.assert_equals(sort_word("add"), "add")
Test.assert_equals(sort_word("address"), "adderss")
Test.assert_equals(sort_word("administration"), "aadiiimnnorstt")
Test.assert_equals(sort_word("admit"), "adimt")
Test.assert_equals(sort_word("adult"), "adltu")
Test.assert_equals(sort_word("affect"), "acefft")
Test.assert_equals(sort_word("after"), "aefrt")
Test.assert_equals(sort_word("again"), "aagin")
Test.assert_equals(sort_word("against"), "aaginst")
Test.assert_equals(sort_word("age"), "aeg")
Test.assert_equals(sort_word("agency"), "acegny")
Test.assert_equals(sort_word("agent"), "aegnt")
Test.assert_equals(sort_word("ago"), "ago")
Test.assert_equals(sort_word("agree"), "aeegr")
Test.assert_equals(sort_word("agreement"), "aeeegmnrt")
Test.assert_equals(sort_word("ahead"), "aadeh")
Test.assert_equals(sort_word("air"), "air")
Test.assert_equals(sort_word("all"), "all")
Test.assert_equals(sort_word("allow"), "allow")
Test.assert_equals(sort_word("almost"), "almost")
Test.assert_equals(sort_word("alone"), "aelno")
Test.assert_equals(sort_word("along"), "aglno")
Test.assert_equals(sort_word("already"), "aadelry")
Test.assert_equals(sort_word("also"), "alos")
Test.assert_equals(sort_word("although"), "aghhlotu")
Test.assert_equals(sort_word("always"), "aalswy")
Test.assert_equals(sort_word("American"), "Aaceimnr")
Test.assert_equals(sort_word("among"), "agmno")
Test.assert_equals(sort_word("amount"), "amnotu")
Test.assert_equals(sort_word("analysis"), "aailnssy")
Test.assert_equals(sort_word("and"), "adn")
Test.assert_equals(sort_word("animal"), "aailmn")
Test.assert_equals(sort_word("another"), "aehnort")
Test.assert_equals(sort_word("answer"), "aenrsw")
Test.assert_equals(sort_word("any"), "any")
Test.assert_equals(sort_word("anyone"), "aennoy")
Test.assert_equals(sort_word("anything"), "aghinnty")
Test.assert_equals(sort_word("appear"), "aaeppr")
Test.assert_equals(sort_word("apply"), "alppy")
Test.assert_equals(sort_word("approach"), "aachoppr")
Test.assert_equals(sort_word("area"), "aaer")
Test.assert_equals(sort_word("argue"), "aegru")
Test.assert_equals(sort_word("arm"), "amr")
Test.assert_equals(sort_word("around"), "adnoru")
Test.assert_equals(sort_word("arrive"), "aeirrv")
Test.assert_equals(sort_word("art"), "art")
Test.assert_equals(sort_word("article"), "aceilrt")
Test.assert_equals(sort_word("artist"), "airstt")
Test.assert_equals(sort_word("as"), "as")
Test.assert_equals(sort_word("ask"), "aks")
Test.assert_equals(sort_word("assume"), "aemssu")
Test.assert_equals(sort_word("at"), "at")
Test.assert_equals(sort_word("attack"), "aacktt")
Test.assert_equals(sort_word("attention"), "aeinnottt")
Test.assert_equals(sort_word("attorney"), "aenortty")
Test.assert_equals(sort_word("audience"), "acdeeinu")
Test.assert_equals(sort_word("author"), "ahortu")
Test.assert_equals(sort_word("authority"), "ahiorttuy")
Test.assert_equals(sort_word("available"), "aaabeillv")
Test.assert_equals(sort_word("avoid"), "adiov")
Test.assert_equals(sort_word("away"), "aawy")
Test.assert_equals(sort_word("baby"), "abby")
Test.assert_equals(sort_word("back"), "abck")
Test.assert_equals(sort_word("bad"), "abd")
Test.assert_equals(sort_word("bag"), "abg")
Test.assert_equals(sort_word("ball"), "abll")
Test.assert_equals(sort_word("bank"), "abkn")
Test.assert_equals(sort_word("bar"), "abr")
Test.assert_equals(sort_word("base"), "abes")
Test.assert_equals(sort_word("be"), "be")
Test.assert_equals(sort_word("beat"), "abet")
Test.assert_equals(sort_word("beautiful"), "abefiltuu")
Test.assert_equals(sort_word("because"), "abceesu")
Test.assert_equals(sort_word("become"), "bceemo")
Test.assert_equals(sort_word("bed"), "bde")
Test.assert_equals(sort_word("before"), "beefor")
Test.assert_equals(sort_word("begin"), "begin")
Test.assert_equals(sort_word("behavior"), "abehiorv")
Test.assert_equals(sort_word("behind"), "bdehin")
Test.assert_equals(sort_word("believe"), "beeeilv")
Test.assert_equals(sort_word("benefit"), "beefint")
Test.assert_equals(sort_word("best"), "best")
Test.assert_equals(sort_word("better"), "beertt")
Test.assert_equals(sort_word("between"), "beeentw")
Test.assert_equals(sort_word("beyond"), "bdenoy")
Test.assert_equals(sort_word("big"), "bgi")
Test.assert_equals(sort_word("bill"), "bill")
Test.assert_equals(sort_word("billion"), "biillno")
Test.assert_equals(sort_word("bit"), "bit")
Test.assert_equals(sort_word("black"), "abckl")
Test.assert_equals(sort_word("blood"), "bdloo")
Test.assert_equals(sort_word("blue"), "belu")
Test.assert_equals(sort_word("board"), "abdor")
Test.assert_equals(sort_word("body"), "bdoy")
Test.assert_equals(sort_word("book"), "bkoo")
Test.assert_equals(sort_word("born"), "bnor")
Test.assert_equals(sort_word("both"), "bhot")
Test.assert_equals(sort_word("box"), "box")
Test.assert_equals(sort_word("boy"), "boy")
Test.assert_equals(sort_word("break"), "abekr")
Test.assert_equals(sort_word("bring"), "bginr")
Test.assert_equals(sort_word("brother"), "behorrt")
Test.assert_equals(sort_word("budget"), "bdegtu")
Test.assert_equals(sort_word("build"), "bdilu")
Test.assert_equals(sort_word("building"), "bdgiilnu")
Test.assert_equals(sort_word("business"), "beinsssu")
Test.assert_equals(sort_word("but"), "btu")
Test.assert_equals(sort_word("buy"), "buy")
Test.assert_equals(sort_word("by"), "by")
Test.assert_equals(sort_word("call"), "acll")
Test.assert_equals(sort_word("camera"), "aacemr")
Test.assert_equals(sort_word("campaign"), "aacgimnp")
Test.assert_equals(sort_word("can"), "acn")
Test.assert_equals(sort_word("cancer"), "accenr")
Test.assert_equals(sort_word("candidate"), "aacddeint")
Test.assert_equals(sort_word("capital"), "aacilpt")
Test.assert_equals(sort_word("car"), "acr")
Test.assert_equals(sort_word("card"), "acdr")
Test.assert_equals(sort_word("care"), "acer")
Test.assert_equals(sort_word("career"), "aceerr")
Test.assert_equals(sort_word("carry"), "acrry")
Test.assert_equals(sort_word("case"), "aces")
Test.assert_equals(sort_word("catch"), "accht")
Test.assert_equals(sort_word("cause"), "acesu")
Test.assert_equals(sort_word("cell"), "cell")
Test.assert_equals(sort_word("center"), "ceenrt")
Test.assert_equals(sort_word("central"), "acelnrt")
Test.assert_equals(sort_word("century"), "cenrtuy")
Test.assert_equals(sort_word("certain"), "aceinrt")
Test.assert_equals(sort_word("certainly"), "aceilnrty")
Test.assert_equals(sort_word("chair"), "achir")
Test.assert_equals(sort_word("challenge"), "aceeghlln")
Test.assert_equals(sort_word("chance"), "accehn")
Test.assert_equals(sort_word("change"), "aceghn")
Test.assert_equals(sort_word("character"), "aaccehrrt")
Test.assert_equals(sort_word("charge"), "aceghr")
Test.assert_equals(sort_word("check"), "ccehk")
Test.assert_equals(sort_word("child"), "cdhil")
Test.assert_equals(sort_word("choice"), "ccehio")
Test.assert_equals(sort_word("choose"), "cehoos")
Test.assert_equals(sort_word("church"), "cchhru")
Test.assert_equals(sort_word("citizen"), "ceiintz")
Test.assert_equals(sort_word("city"), "city")
Test.assert_equals(sort_word("civil"), "ciilv")
Test.assert_equals(sort_word("claim"), "acilm")
Test.assert_equals(sort_word("class"), "aclss")
Test.assert_equals(sort_word("clear"), "acelr")
Test.assert_equals(sort_word("clearly"), "acellry")
Test.assert_equals(sort_word("close"), "celos")
Test.assert_equals(sort_word("coach"), "accho")
Test.assert_equals(sort_word("cold"), "cdlo")
Test.assert_equals(sort_word("collection"), "cceillnoot")
Test.assert_equals(sort_word("college"), "ceegllo")
Test.assert_equals(sort_word("color"), "cloor")
Test.assert_equals(sort_word("come"), "cemo")
Test.assert_equals(sort_word("commercial"), "acceilmmor")
Test.assert_equals(sort_word("common"), "cmmnoo")
Test.assert_equals(sort_word("community"), "cimmnotuy")
Test.assert_equals(sort_word("company"), "acmnopy")
Test.assert_equals(sort_word("compare"), "acemopr")
Test.assert_equals(sort_word("computer"), "cemoprtu")
Test.assert_equals(sort_word("concern"), "ccennor")
Test.assert_equals(sort_word("condition"), "cdiinnoot")
Test.assert_equals(sort_word("conference"), "cceeefnnor")
Test.assert_equals(sort_word("Congress"), "Cegnorss")
Test.assert_equals(sort_word("consider"), "cdeinors")
Test.assert_equals(sort_word("consumer"), "cemnorsu")
Test.assert_equals(sort_word("contain"), "acinnot")
Test.assert_equals(sort_word("continue"), "ceinnotu")
Test.assert_equals(sort_word("control"), "clnoort")
Test.assert_equals(sort_word("cost"), "cost")
Test.assert_equals(sort_word("could"), "cdlou")
Test.assert_equals(sort_word("country"), "cnortuy")
Test.assert_equals(sort_word("couple"), "celopu")
Test.assert_equals(sort_word("course"), "ceorsu")
Test.assert_equals(sort_word("court"), "cortu")
Test.assert_equals(sort_word("cover"), "ceorv")
Test.assert_equals(sort_word("create"), "aceert")
Test.assert_equals(sort_word("crime"), "ceimr")
Test.assert_equals(sort_word("cultural"), "acllrtuu")
Test.assert_equals(sort_word("culture"), "celrtuu")
Test.assert_equals(sort_word("cup"), "cpu")
Test.assert_equals(sort_word("current"), "cenrrtu")
Test.assert_equals(sort_word("customer"), "cemorstu")
Test.assert_equals(sort_word("cut"), "ctu")
Test.assert_equals(sort_word("dark"), "adkr")
Test.assert_equals(sort_word("data"), "aadt")
Test.assert_equals(sort_word("daughter"), "adeghrtu")
Test.assert_equals(sort_word("day"), "ady")
Test.assert_equals(sort_word("dead"), "adde")
Test.assert_equals(sort_word("deal"), "adel")
Test.assert_equals(sort_word("death"), "adeht")
Test.assert_equals(sort_word("debate"), "abdeet")
Test.assert_equals(sort_word("decade"), "acddee")
Test.assert_equals(sort_word("decide"), "cddeei")
Test.assert_equals(sort_word("decision"), "cdeiinos")
Test.assert_equals(sort_word("deep"), "deep")
Test.assert_equals(sort_word("defense"), "deeefns")
Test.assert_equals(sort_word("degree"), "deeegr")
Test.assert_equals(sort_word("Democrat"), "Dacemort")
Test.assert_equals(sort_word("democratic"), "accdeimort")
Test.assert_equals(sort_word("describe"), "bcdeeirs")
Test.assert_equals(sort_word("design"), "degins")
Test.assert_equals(sort_word("despite"), "deeipst")
Test.assert_equals(sort_word("detail"), "adeilt")
Test.assert_equals(sort_word("determine"), "deeeimnrt")
Test.assert_equals(sort_word("develop"), "deelopv")
Test.assert_equals(sort_word("development"), "deeelmnoptv")
Test.assert_equals(sort_word("die"), "dei")
Test.assert_equals(sort_word("difference"), "cdeeeffinr")
Test.assert_equals(sort_word("different"), "deeffinrt")
Test.assert_equals(sort_word("difficult"), "cdffiiltu")
Test.assert_equals(sort_word("dinner"), "deinnr")
Test.assert_equals(sort_word("direction"), "cdeiinort")
Test.assert_equals(sort_word("director"), "cdeiorrt")
Test.assert_equals(sort_word("discover"), "cdeiorsv")
Test.assert_equals(sort_word("discuss"), "cdisssu")
Test.assert_equals(sort_word("discussion"), "cdiinosssu")
Test.assert_equals(sort_word("disease"), "adeeiss")
Test.assert_equals(sort_word("do"), "do")
Test.assert_equals(sort_word("doctor"), "cdoort")
Test.assert_equals(sort_word("dog"), "dgo")
Test.assert_equals(sort_word("door"), "door")
Test.assert_equals(sort_word("down"), "dnow")
Test.assert_equals(sort_word("draw"), "adrw")
Test.assert_equals(sort_word("dream"), "ademr")
Test.assert_equals(sort_word("drive"), "deirv")
Test.assert_equals(sort_word("drop"), "dopr")
Test.assert_equals(sort_word("drug"), "dgru")
Test.assert_equals(sort_word("during"), "dginru")
Test.assert_equals(sort_word("each"), "aceh")
Test.assert_equals(sort_word("early"), "aelry")
Test.assert_equals(sort_word("east"), "aest")
Test.assert_equals(sort_word("easy"), "aesy")
Test.assert_equals(sort_word("eat"), "aet")
Test.assert_equals(sort_word("economic"), "cceimnoo")
Test.assert_equals(sort_word("economy"), "cemnooy")
Test.assert_equals(sort_word("edge"), "deeg")
Test.assert_equals(sort_word("education"), "acdeinotu")
Test.assert_equals(sort_word("effect"), "ceefft")
Test.assert_equals(sort_word("effort"), "effort")
Test.assert_equals(sort_word("eight"), "eghit")
Test.assert_equals(sort_word("either"), "eehirt")
Test.assert_equals(sort_word("election"), "ceeilnot")
Test.assert_equals(sort_word("else"), "eels")
Test.assert_equals(sort_word("employee"), "eeelmopy")
Test.assert_equals(sort_word("end"), "den")
Test.assert_equals(sort_word("energy"), "eegnry")
Test.assert_equals(sort_word("enjoy"), "ejnoy")
Test.assert_equals(sort_word("enough"), "eghnou")
Test.assert_equals(sort_word("enter"), "eenrt")
Test.assert_equals(sort_word("entire"), "eeinrt")
Test.assert_equals(sort_word("environment"), "eeimnnnortv")
Test.assert_equals(sort_word("environmental"), "aeeilmnnnortv")
Test.assert_equals(sort_word("especially"), "aceeillpsy")
Test.assert_equals(sort_word("establish"), "abehilsst")
Test.assert_equals(sort_word("even"), "eenv")
Test.assert_equals(sort_word("evening"), "eeginnv")
Test.assert_equals(sort_word("event"), "eentv")
Test.assert_equals(sort_word("ever"), "eerv")
Test.assert_equals(sort_word("every"), "eervy")
Test.assert_equals(sort_word("everybody"), "bdeeorvyy")
Test.assert_equals(sort_word("everyone"), "eeenorvy")
Test.assert_equals(sort_word("everything"), "eeghinrtvy")
Test.assert_equals(sort_word("evidence"), "cdeeeinv")
Test.assert_equals(sort_word("exactly"), "aceltxy")
Test.assert_equals(sort_word("example"), "aeelmpx")
Test.assert_equals(sort_word("executive"), "ceeeituvx")
Test.assert_equals(sort_word("exist"), "eistx")
Test.assert_equals(sort_word("expect"), "ceeptx")
Test.assert_equals(sort_word("experience"), "ceeeeinprx")
Test.assert_equals(sort_word("expert"), "eeprtx")
Test.assert_equals(sort_word("explain"), "aeilnpx")
Test.summary()



def zip_it(women, men):
      if len(women) != len(men):
            return "sizes don't match"
      else:
            return list(zip(women, men))
      


Test.assert_equals(zip_it(["Elise", "Mary"], ["John", "Rick"]), [("Elise", "John"), ("Mary", "Rick")])
Test.assert_equals(zip_it(["Ana", "Amy", "Lisa"], ["Bob", "Josh"]), "sizes don't match")
Test.assert_equals(zip_it(["Ana", "Amy", "Lisa"], ["Bob", "Josh", "Tim"]), [("Ana", "Bob"), ("Amy", "Josh"), ("Lisa", "Tim")])
Test.assert_equals(zip_it(["Ana", "Amy", "Lisa", "Katty"], ["Bob", "Josh", "Tim"]), "sizes don't match")
Test.assert_equals(zip_it(["Katty", "Ana", "Amy", "Lisa"], ["Bob", "Josh", "Tim", "Aaron"]), [("Katty", "Bob"), ("Ana", "Josh"), ("Amy", "Tim"), ("Lisa", "Aaron")])
Test.summary()


def age_difference(ages):
      if sorted(ages)[-1] != sorted(ages)[-2] :
            age = sorted(ages)[-1] - sorted(ages)[-2]
            if age > 1:
                  return str(age) + " years"
            else:
                  return str(age) + " year"
      
      else:
            return "No age difference between spouses."

Test.assert_equals(age_difference([29, 1, 6, 8, 28]), "1 year")
Test.assert_equals(age_difference([43, 86, 49, 86]), "No age difference between spouses.")
Test.assert_equals(age_difference([2, 4, 6, 32, 27]), "5 years")
Test.assert_equals(age_difference([55, 28, 25, 56, 20]), "1 year")
Test.assert_equals(age_difference([21, 56, 69, 18]), "13 years")
Test.assert_equals(age_difference([25, 70, 25, 26, 58]), "12 years")
Test.assert_equals(age_difference([10, 12, 44, 9, 44]), "No age difference between spouses.")
Test.summary()


def longest_string(str1, str2):
      return ''.join(sorted(set(str1 + str2)))
      

Test.assert_equals(longest_string("mubashir", "edabit"), "abdehimrstu")
Test.assert_equals(longest_string("pakistan", "airforce"), "acefiknoprst")
Test.assert_equals(longest_string("", "e"), "e")
Test.assert_equals(longest_string("", ""), "")
Test.assert_equals(longest_string("noooo", "yesssss"), "enosy")
Test.assert_equals(longest_string("aretheyhere", "yestheyarehere"), "aehrsty")
Test.assert_equals(longest_string("loopingisfunbutdangerous", "lessdangerousthancoding"), "abcdefghilnoprstu")
Test.assert_equals(longest_string("inmanylanguages", "theresapairoffunctions"), "acefghilmnoprstuy")
Test.assert_equals(longest_string("lordsofthefallen", "gamekult"), "adefghklmnorstu")
Test.summary()


def even_odd_string(txt):
    eve = txt[::2]
    d = txt[1::2]
    return eve + " " + d

Test.assert_equals(even_odd_string("mubashir"), "mbsi uahr")
Test.assert_equals(even_odd_string("edabit"), "eai dbt")
Test.assert_equals(even_odd_string("airforce"), "aroc ifre")
Test.assert_equals(even_odd_string("Wolfeschlegelsteinhausenbergerdorff"), "Wleclgltihuebredrf ofsheesenasnegrof")
Test.assert_equals(even_odd_string("METHIONYLTHREONYLTHREONYGLUTAMINYLARGINYL"), "MTINLHENLHENGUAIYAGNL EHOYTROYTROYLTMNLRIY")
Test.assert_equals(even_odd_string("PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS"), "PEMNUTAIRSOISLCVLAOOISS NUOOLRMCOCPCIIOOCNCNOI")
Test.assert_equals(even_odd_string("PSEUDOPSEUDOHYPOPARATHYROIDISM"), "PEDPEDHPPRTYODS SUOSUOYOAAHRIIM")
Test.assert_equals(even_odd_string("FLOCCINAUCINIHILIPILIFICATION"), "FOCNUIIIIIIIAIN LCIACNHLPLFCTO")
Test.assert_equals(even_odd_string("SUBDERMATOGLYPHIC"),"SBEMTGYHC UDRAOLPI")
Test.summary()


def reverse(txt):
      return txt[::-1]

print(reverse("Hello World"))  # ➞ "dlroW olleH"
Test.assert_equals(reverse("Think different."), ".tnereffid knihT")
Test.assert_equals(reverse("It doesn't make sense to hire smart people and tell them what to do; we hire smart people so they can tell us what to do."), ".od ot tahw su llet nac yeht os elpoep trams erih ew ;od ot tahw meht llet dna elpoep trams erih ot esnes ekam t'nseod tI")
Test.assert_equals(reverse("Innovation is the ability to see change as an opportunity - not a threat"), "taerht a ton - ytinutroppo na sa egnahc ees ot ytiliba eht si noitavonnI")
Test.assert_equals(reverse("Everything is based on a simple rule: Quality is the best business plan."), ".nalp ssenisub tseb eht si ytilauQ :elur elpmis a no desab si gnihtyrevE")
Test.assert_equals(reverse("The people who are crazy enough to think they can change the world are the ones who do."), ".od ohw seno eht era dlrow eht egnahc nac yeht kniht ot hguone yzarc era ohw elpoep ehT")
Test.assert_equals(reverse("Don't let the noise of others' opinions drown out your own inner voice."), ".eciov renni nwo ruoy tuo nword snoinipo 'srehto fo esion eht tel t'noD")
Test.assert_equals(reverse("Learn continually; There's always one more thing to learn."), ".nrael ot gniht erom eno syawla s'erehT ;yllaunitnoc nraeL")
Test.assert_equals(reverse("Quality is more important than quantity. One home run is much better than two doubles."), ".selbuod owt naht retteb hcum si nur emoh enO .ytitnauq naht tnatropmi erom si ytilauQ")
Test.assert_equals(reverse("Your time is limited so don't waste it living someone else's life."), ".efil s'esle enoemos gnivil ti etsaw t'nod os detimil si emit ruoY")
Test.assert_equals(reverse("The only way to be truly satisfied is to do what you believe is great work."), ".krow taerg si eveileb uoy tahw od ot si deifsitas ylurt eb ot yaw ylno ehT")
Test.assert_equals(reverse("#$*+-=:;/\\@<>?_][`{}|~^'&%$#\"!"), "!\"#$%&'^~|}{`[]_?><@\/;:=-+*$#")
Test.summary()



def findLargestNums(lst):
      return list(map(max, lst))


Test.assert_equals(findLargestNums([[4, 2, 7, 1], [20, 70, 40, 90], [1, 2, 0]]), [7, 90, 2])
Test.assert_equals(findLargestNums([[0.4321, 0.7634, 0.652], [1.324, 9.32, 2.5423, 6.4314], [9, 3, 6, 3]]), [0.7634, 9.32, 9])
Test.assert_equals(findLargestNums([[-34, -54, -74], [-32, -2, -65], [-54, 7, -43]]), [-34, -2, 7])
Test.assert_equals(findLargestNums([[0.34, -5, 1.34], [-6.432, -1.762, -1.99], [32, 65, -6]]), [1.34, -1.762, 65])
Test.assert_equals(findLargestNums([[0, 0, 0, 0], [3, 3, 3, 3], [-2, -2]]), [ 0, 3, -2 ])
Test.summary()


def list_values_types(lst):
      return [type(i).__name__ for i in lst]


Test.assert_equals(list_values_types([1, 10]), ['int', 'int'])
Test.assert_equals(list_values_types([["hello" , 1]  , 10]), ['list', 'int'])
Test.assert_equals(list_values_types(["shashwat", 10, 90]), ['str', 'int', 'int'])
Test.assert_equals(list_values_types([[], True]), ['list', 'bool'])
Test.assert_equals(list_values_types([False, False, "true"]), ['bool', 'bool', "str"])
Test.assert_equals(list_values_types([1, 10]), ['int', 'int'])
Test.assert_equals(list_values_types([[], None]), ['list', 'NoneType'])
Test.assert_equals(list_values_types([1.23, 10]), ['float', 'int'])
Test.assert_equals(list_values_types([{1: 'one', 2: 'two'}, []]), ['dict', 'list'])
Test.summary()


#done